### ISSUE TITLE
关于代码加密

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [pjy612/Bilibili-LRHH#12]
8283aae12de2088b2204ea415a8f6d10aaed177c
7f1a00f8bc0eabde3de91c01dcf28d7953579c90
不会吧不会吧，不会真有人花钱把**开源的代码**搞一个加密吧
球球宁了，别恶心👴了，开源代码还搞加密的多少沾点吧
这就是宁的代码？在GreasyFork因为逻辑不公开下架之后继续在GitHub上面搞加密？(D区)
💉💧是有够好笑的呢
`6L+Z5bCx5piv5Y+N56S+5Lya5Lq65qC86ams77yf55yf5piv6ZW/55+l6K+G5LqG5ZGifgo=`

**Comment by pjy612** [comment]
没花钱，一些暂时不适合开源的代码随便混淆处理了下。
而且脚本已明确说明包含恶意功能，其他的你们开心就好

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 没花钱，一些暂时不适合开源的代码随便混淆处理了下。
> 而且脚本已明确说明包含恶意功能，其他的你们开心就好

那么我想知道，关于`不适合开源`具体指的是什么

- API接口抓包就能抓到
    
- 送心的逻辑这个也没必要加密

何必多此一举去加密代码，看着不舒服不说还降低性能

**Comment by pjy612** [comment]
快速挂心的逻辑。
另外如果你觉得不适合，可以不用，改用原版和其他gf的脚本或客户端，如果技术好也可以自己再二次魔改啥的。
我这个自娱自乐的小项目容不下您这种标杆大牛。所以恕不奉陪了。
