### ISSUE TITLE
bilibiliapi初始化失败

### ISSUE THREAD

**Issue by gzx7301** [pjy612/Bilibili-LRHH#13]
**描述bug**
bilibiliapi初始化失败

**重现bug**
1.更新脚本

**预期行为**
本应正常工作 却显示bilibili api初始化失败

**截图**
怎么上传截图？

**使用环境:**
Microsoft Edge | 84.0.522.40 (官方内部版本) (64 位)
-- | --
修订 | 4ede1b0ab15e7ee434735507aa3e79d88ef95c48
操作系统 | Windows 8.1 (Build 9600.19652)
JavaScript | V8 8.4.371.19
 - 脚本的版本:2.4.5.11
 - 网络情况(网速): 好
 - 其他浏览器插件/脚本: 没有
 - bug出现时间: 脚本更新后

**其他**
更新后出现的bug

**Comment by pjy612** [comment]
截图的话 QQ 微信截图后 直接粘贴在 输入框应该就好了。
不过 github 现在 资源服务器不太好 所以 很多看不了。
5.11版的话 将 依赖库 地址 换成了 https://github.com.cnpmjs.org/ 镜像站。
结果 本地网络没问题 你们好像部分不能访问。
然后 5.12 就又换回去了 ╮(￣▽￣")╭ 
不过 5.11 送礼 有bug 推荐更新 5.12 或者 降到 5.10
