### ISSUE TITLE
自动休眠

### ISSUE THREAD

**Issue by Superbia000** [pjy612/Bilibili-LRHH#2]
希望能增加固定时间段的自动休眠功能
例如: 03-08点

**Comment by pjy612** [comment]
d1149324378af21a369cabce5124211e24e57654
a64dddfbcbaba33227c44cc532c037e12d61f58d
d0ebf4f54890deed5dae458bc27966b599fa217b
已处理

**Comment by Superbia000** [comment]
设置了时间还是会自动抽奖
3:00-8:00
03:00-08:00
都试过

**Comment by pjy612** [comment]
> 设置了时间还是会自动抽奖
> 3:00-8:00
> 03:00-08:00
> 都试过

是有问题 周六改过了
