### ISSUE TITLE
建议换jQuery的来源

### ISSUE THREAD

**Issue by Janet-Baker** [pjy612/Bilibili-LRHH#4]
建议将jQuery的来源换成jsdelivr的，网络状况要好很多，毕竟jQuery有国内网宿科技和百度云加速的cdn节点。

13 `// @require      https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js`

另外不考虑一下向README里面再加几个下载地址吗？raw.git什么的是真的上不去，直连github都要靠运气。比如长江和jsdelivr的地址（当然最好指定版本，jsdelivr的不指定版本缓存周期非常长）

`https://cdn.jsdelivr.net/gh/pjy612/Bilibili-LRHH/Bilibili%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B-%E9%AD%94%E6%94%B9.user.js`

顺便，发现了一个问题：刷新的时候为什么要切换成html5播放器呢？每一次传送门跳转都会从Flash播放器换成HTML5播放器。加载了播放器之后内存瞬间加倍，1G起步。

最后，留言难道只能发issues了吗……

**Comment by WankkoRee** [comment]
jQuery的默认源我也觉得可以改改。

不过关于用jsdelivr作为下载地址的事情，这个只针对手动点击安装时有效果。
油猴脚本对于检查更新的来源优先级处理上，脚本内置的更新链接比安装时的来源链接优先级要高，所以后续在脚本管理器中更新的话，又会出现网络问题。而jsdelivr的指定版本我记得似乎需要每次发版release才行？而且指定版本的链接相当于又断了更新的后路，无法在理想情况下（从安装时的来源链接检查更新）检查更新。

最后H5和Fl的切换，不太了解。

**Comment by pjy612** [comment]
H5 是确保你打开看了 ╮(￣▽￣")╭

**Comment by pjy612** [comment]
主脚本不太行。。。毕竟CDN刷新不可控。。。jquery已更
