### ISSUE TITLE
可以自己搭建一个bilibilipush服务器吗？

### ISSUE THREAD

**Issue by Initial-heart-1** [pjy612/Bilibili-LRHH#9]
可以自己搭建一个bilibilipush服务器吗？DD门属实可怕，晚上给我吓醒

**Comment by Initial-heart-1** [comment]
不开push效率属实低（相对

**Comment by pjy612** [comment]
你可以自己搭个监控，然后看看怎么对接脚本，你也可以自己研究对接外面的 ws 监控。
客户端都开源了随便改。

**Comment by popo-bear** [comment]
> 可以自己搭建一个bilibilipush服务器吗？DD门属实可怕，晚上给我吓醒

其实没必要了，就几天时间了，今天舰队已经下了，2020年7月24日11时，下线舰队宝箱及奖励功能。   乱斗按通知最多到26日结束为止。

撑死下周，所有抽奖活动会全面下线。
